### ISSUE TITLE
Operations piped to events stream doesn't seem to run

### ISSUE THREAD

**Issue by michaek** [floatdrop/gulp-batch#14]
I'm trying the example from the Readme, and I don't seem to get any console output.

```javascript
gulp.watch(['../some/path/*'], batch(function(events) {
	console.log('batch');
	return events.pipe(console.log);
}));
```

Whenever I make a change to a matching file, the "batch" log is output, but nothing else. Is there something obvious I'm missing?

Thanks!

**Comment by floatdrop** [comment]
Example in readme is horribly wrong, here is right one:

```js
var gulp = require('gulp');
var batch = require('gulp-batch');
var debug = require('gulp-debug');

gulp.watch(['lib/**', 'test/**'], batch(function(events) {
    return events.pipe(debug());
}));
```

**Comment by dannyfritz** [comment]
Could you bump the version and republish to npmjs so the README is updated there too?

**Comment by floatdrop** [comment]
@dannyfritz done.
