### ISSUE TITLE
Allow task names instead of callback function

### ISSUE THREAD

**Issue by andrenarchy** [floatdrop/gulp-batch#15]
It would be great if gulp-batch would support to run tasks additional to callback functions. Example:

```
gulp.watch('build/**/*', batch('serve:reload'));
```

Currently, I have to use `gulp.run` for this:

```
gulp.watch('build/**/*', batch(function(events, done) {
  gulp.run('serve:reload');
}));
```

However, `gulp.run` is deprecated:

```
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
```

**Comment by floatdrop** [comment]
gulp plugins does not have alternate way to call tasks besides `gulp.run`, which is deprecated. You can open issue about it in [gulp repository](https://github.com/gulpjs/gulp/issues).

**Comment by andrenarchy** [comment]
The alternative is `gulp.start`, see https://github.com/gulpjs/gulp/issues/426.
